import fs from 'fs';
import path from 'path';

export const VU_OFFICIAL_TITLES: Record<string, string> = {
  // Accounting & Finance
  ACC301: 'Financial Accounting',
  ACC311: 'Fundamentals of Auditing',
  ACC501: 'Business Finance',
  BNK601: 'Banking Laws & Practices',
  BNK603: 'Consumer Banking',
  BNK604: 'Commercial Banking',
  BNK610: 'Credit & Risk Management in Banking',
  FIN611: 'Advanced Financial Accounting',
  FIN621: 'Financial Statement Analysis',
  FIN622: 'Corporate Finance',
  FIN623: 'Taxation Management',
  FIN624: 'Islamic Banking & Finance',
  FIN625: 'Credit & Risk Management',
  FIN630: 'Investment Analysis & Portfolio Management',
  FIN722: 'Advanced Corporate Finance',
  EFIN623: 'Economics of Financial Markets',

  // Computer Science & IT
  CS000: 'Introduction to Computer Fundamentals',
  CS001: 'Computer Proficiency License',
  CS101: 'Introduction to Computing',
  CS201: 'Introduction to Programming',
  CS201P: 'Introduction to Programming (Practical)',
  CS202: 'Web Design & Development',
  CS204: 'Cyber Law & Intellectual Property',
  CS205: 'Information Security Management',
  CS206: 'Ethical Hacking & Defense',
  CS301: 'Data Structures',
  CS301P: 'Data Structures (Practical)',
  CS302: 'Digital Logic Design',
  CS302P: 'Digital Logic Design (Practical)',
  CS304: 'Object Oriented Programming',
  CS304P: 'Object Oriented Programming (Practical)',
  CS310: 'Introduction to Programming (Python)',
  CS311: 'Introduction to Web Services Development',
  CS312: 'Mobile Application Development',
  CS314: 'Embedded Systems & IoT',
  CS315: 'Web Engineering',
  CS401: 'Computer Architecture & Assembly Language',
  CS402: 'Theory of Automata',
  CS403: 'Database Management Systems',
  CS403P: 'Database Management Systems (Practical)',
  CS405: 'Mobile Computing',
  CS407: 'Cloud Computing Fundamentals',
  CS408: 'Human Computer Interaction',
  CS409: 'Ethical & Legal Issues in Computing',
  CS410: 'Design & Analysis of Algorithms',
  CS411: 'Visual Programming',
  CS420: 'Game Design and Development',
  CS432: 'Network Security',
  CS435: 'Cloud Computing Infrastructure',
  CS501: 'Advance Computer Architecture',
  CS502: 'Fundamentals of Algorithms',
  CS504: 'Software Engineering - I',
  CS505: 'Agile Software Development',
  CS506: 'Enterprise Application Development',
  CS507: 'Information Systems',
  CS508: 'Modern Programming Languages',
  CS510: 'Compiler Construction',
  CS511: 'Distributed Systems',
  CS521: 'Data Science Principles',
  CS601: 'Data Communication',
  CS602: 'Computer Graphics',
  CS603: 'Software Architecture',
  CS604: 'Operating Systems',
  CS605: 'Software Engineering - II',
  CS606: 'Compiler Design & Construction',
  CS607: 'Artificial Intelligence',
  CS608: 'Digital Signal Processing',
  CS609: 'System Programming',
  CS610: 'Computer Networks',
  CS611: 'Software Quality Assurance',
  CS614: 'Data Warehousing',
  CS615: 'Software Project Management',
  CS619: 'Final Year Project',
  CS621: 'Information Retrieval Techniques',
  CS625: 'Formal Methods in Software Engineering',
  CS627: 'Computer Vision & Pattern Recognition',
  CS636: 'Big Data Analytics',
  CS708: 'Advanced Computer Graphics',
  CS713: 'Advanced Software Architecture',
  CS718: 'Advanced Artificial Intelligence',
  IT430: 'E-Commerce & Digital Business',
  IT601: 'Network Administration',
  IT602: 'Database Administration',
  ITU430: 'E-Commerce Systems',

  // Mathematics & Statistics
  MTH001: 'Elementary Mathematics',
  MTH100: 'General Mathematics',
  MTH101: 'Calculus & Analytical Geometry',
  MTH104: 'Sets & Logic',
  MTH202: 'Discrete Mathematics',
  MTH301: 'Calculus II (Multivariable Calculus)',
  MTH302: 'Business Mathematics & Statistics',
  MTH401: 'Differential Equations',
  MTH501: 'Linear Algebra',
  MTH601: 'Operations Research',
  MTH603: 'Numerical Analysis',
  MTH622: 'Vector & Tensor Analysis',
  MTH631: 'Real Analysis',
  MTH632: 'Complex Analysis',
  MTH634: 'Topology',
  MTH641: 'Functional Analysis',
  MTH644: 'Mathematical Methods',
  MTH645: 'Mechanics',
  MTH646: 'Differential Geometry',
  MTH647: 'Fluid Mechanics',
  STA000: 'Basic Statistics Fundamentals',
  STA100: 'Foundations of Statistics',
  STA301: 'Statistics and Probability',
  STA304: 'Statistical Inference',
  STA404: 'Experimental Design',
  STA406: 'Sampling Techniques',
  STA408: 'Biostatistics and Epidemiology',
  STA630: 'Research Methods in Social Sciences',
  STA631: 'Advanced Statistical Methods',
  STA632: 'Multivariate Analysis',
  STA641: 'Non-Parametric Methods',
  STA642: 'Econometric Models',
  STA730: 'Advanced Research Methodology in Statistics',
  STAT100: 'Statistics Fundamentals',
  STAT404: 'Applied Statistical Modeling',
  STAT408: 'Statistical Computing',
  STAT730: 'Advanced Biostatistics',
  DSTA630: 'Data Science Research Methods',

  // Physics & Chemistry & Sciences
  PHY000: 'Foundational Physics',
  PHY101: 'Physics - Mechanics & Waves',
  PHY301: 'Circuit Theory',
  CHE201: 'General Chemistry',
  CHE301: 'Organic Chemistry',
  GSC101: 'General Science',

  // Biological Sciences & Zoology
  BIO101: 'Basic Biology',
  BIO102: 'Introductory Biology & Diversity',
  BIO201: 'Cell Biology',
  BIO202: 'Biochemistry',
  BIO203: 'General Genetics',
  BIO204: 'Biochemical Techniques',
  BIO301: 'Molecular Biology',
  BIO302: 'Animal Physiology',
  BIO303: 'Developmental Biology',
  BIO401: 'Ecology & Evolutionary Biology',
  BIO502: 'Immunology & Pathology',
  BIO503: 'Pharmacology & Toxicology',
  BIO504: 'Applied Microbiology',
  BIO505: 'Environmental Biotechnology',
  BIO506: 'Forensic Biology',
  BIO731: 'Advanced Molecular Genetics',
  BIF101: 'Basic Bioinformatics',
  BIF401: 'Introduction to Bioinformatics',
  BIF402: 'Computational Biology Methods',
  BIF501: 'Genomics & Proteomics',
  BIF601: 'Bioinformatics Algorithms',
  BIF602: 'Structural Bioinformatics',
  BIF604: 'Systems Biology',
  BT101: 'Ecology, Biodiversity & Evolution',
  BT102: 'Microbiology',
  BT201: 'Biotechnology Fundamentals',
  BT301: 'Recombinant DNA Technology',
  BT302: 'Cell and Tissue Culture',
  BT401: 'Genetic Engineering',
  BT402: 'Fermentation Technology',
  BT403: 'Agricultural Biotechnology',
  BT404: 'Medical Biotechnology',
  BT405: 'Industrial Biotechnology',
  BT406: 'Nanobiotechnology',
  BT501: 'Biochemical Engineering',
  BT502: 'Biosafety & Bioethics',
  BT503: 'Molecular Diagnostics',
  BT504: 'Stem Cell Technology',
  BT505: 'Food Biotechnology',
  BT511: 'Vaccine Technology',
  BT512: 'Drug Design & Development',
  BT513: 'Genomics & Functional Proteomics',
  BT514: 'Enzyme Technology',
  BT601: 'Advanced Genetic Engineering',
  BT602: 'Bioinformatics in Biotechnology',
  BT603: 'Bioprocess Engineering',
  BT604: 'Aquatic Biotechnology',
  BT605: 'Environmental Bioremediation',
  BT611: 'Synthetic Biology',
  BT612: 'Metabolic Engineering',
  BT613: 'Biofuels and Bioenergy',
  BT614: 'Clinical Research in Biotechnology',
  BT693: 'Research Project in Biotechnology',
  BT732: 'Advanced Molecular Biology Seminar',
  BT734: 'Advanced Cellular Biotechnology',
  BT735: 'Current Topics in Biotechnology',
  NTBT301: 'Nanotechnology in Biotechnology',
  MB501: 'General Microbiology & Microbial Diversity',
  MB502: 'Microbial Physiology & Metabolism',
  MB504: 'Medical Microbiology',
  MIC501: 'Applied Microbiology',
  ZOO101: 'Principles of Animal Life I',
  ZOO102: 'Principles of Animal Life II',
  ZOO103: 'Animal Diversity: Invertebrates',
  ZOO111: 'Fundamentals of Zoology',
  ZOO201: 'Animal Diversity: Chordates',
  ZOO202: 'Animal Form & Function I',
  ZOO203: 'Animal Form & Function II',
  ZOO301: 'Animal Physiology',
  ZOO302: 'Cell & Molecular Biology in Zoology',
  ZOO307: 'Principles of Ecology',
  ZOO401: 'Evolution & Principles of Systematics',
  ZOO403: 'Animal Behavior & Sociobiology',
  ZOO404: 'Biostatistics for Zoologists',
  ZOO405: 'General Developmental Biology',
  ZOO501: 'Developmental Biology',
  ZOO502: 'Environmental Biology',
  ZOO503: 'Biostatistics in Zoological Research',
  ZOO504: 'Zoogeography & Paleontology',
  ZOO505: 'Wildlife of Pakistan & Conservation',
  ZOO506: 'Endocrinology',
  ZOO507: 'Animal Diversity & Behavior',
  ZOO509: 'Fish Biology & Fisheries Science',
  ZOO510: 'General Microbiology & Immunology',
  ZOO511: 'Immunology & Serology',
  ZOO512: 'Parasitology & Vectors',
  ZOO513: 'Applied Entomology',
  ZOO514: 'Biochemistry of Animals',
  ZOO515: 'Genetics & Population Biology',
  ZOO516: 'Aquaculture & Fisheries Management',
  ZOO517: 'Toxicology & Environmental Health',
  ZOO518: 'Comparative Vertebrate Anatomy',
  ZOO519: 'Mammalogy',
  ZOO520: 'Ornithology (Bird Biology)',
  ZOO603: 'Applied Parasitology & Vector Biology',
  ZOO630: 'Research Methodology in Zoology',

  // English & Linguistics
  ENG001: 'Basic English Grammar & Composition',
  ENG101: 'English Comprehension',
  ENG201: 'Business and Technical English Writing',
  ENG301: 'Business Communication',
  ENG501: 'History of English Language',
  ENG502: 'Introduction to Linguistics',
  ENG503: 'English Morphology and Syntax',
  ENG504: 'Sociolinguistics',
  ENG505: 'Phonetics & Phonology',
  ENG506: 'World Englishes',
  ENG507: 'Psycholinguistics',
  ENG508: 'Semantics & Pragmatics',
  ENG509: 'English for Specific Purposes (ESP)',
  ENG510: 'Language Testing & Evaluation',
  ENG511: 'Syllabus Design & Materials Development',
  ENG512: 'Stylistics & Literary Analysis',
  ENG513: 'Second Language Acquisition (SLA)',
  ENG514: 'Classical Poetry',
  ENG515: 'Classical Drama',
  ENG516: 'Research Methodology in Linguistics',
  ENG517: 'Modern Poetry',
  ENG518: 'Modern Drama',
  ENG519: 'Classical Novel',
  ENG520: 'Modern Novel',
  ENG521: 'American Literature',
  ENG522: 'Postcolonial Literature',
  ENG523: 'Continental Literature & Criticism',
  ENG524: 'Literary Criticism & Theory',
  ENG525: 'Discourse Analysis',
  ENG526: 'Applied Linguistics in Education',
  ENG527: 'Creative Writing & Composition',
  ENG528: 'Corpus Linguistics',
  ENG529: 'Translation Studies & Theory',
  FENG301: 'Functional English for Professionals',

  // Education
  EDU101: 'Foundations of Education',
  EDU201: 'Learning Theories & Applications',
  EDU205: 'Classroom Management',
  EDU301: 'General Methods of Teaching',
  EDU302: 'Human Development & Learning',
  EDU303: 'School, Community and Teacher',
  EDU304: 'Educational Assessment & Evaluation',
  EDU305: 'Curriculum Development & Instruction',
  EDU306: 'Contemporary Trends in Education',
  EDU401: 'Critical Thinking and Reflective Practices',
  EDU402: 'Educational Leadership & Management',
  EDU403: 'Art, Craft & Calligraphy in Education',
  EDU404: 'Teaching of English',
  EDU405: 'Teaching of Mathematics',
  EDU406: 'Teaching of General Science',
  EDU410: 'ICT in Education',
  EDU411: 'Teaching of Social Studies',
  EDU430: 'Information & Communication Technology in Teaching',
  EDU431: 'Test Development & Measurement',
  EDU433: 'Educational Statistics',
  EDU501: 'Educational Psychology',
  EDU505: 'Guidance and Counseling in Schools',
  EDU510: 'Qualitative Research in Education',
  EDU512: 'Comparative Education',
  EDU514: 'Special Education Principles',
  EDU515: 'Early Childhood Education Curriculum',
  EDU516: 'Educational Technology & Media',
  EDU601: 'Philosophy of Education',
  EDU602: 'Educational Planning and Policy',
  EDU604: 'Educational Administration & Supervision',
  EDU630: 'Research Methods in Education',
  EDU654: 'Teacher Education in Pakistan',
  EDU702: 'Advanced Seminar in Educational Leadership',
  EDU705: 'Advanced Educational Policy Analysis',
  EDUA305: 'Applied Curriculum Development',
  EDUA403: 'Elementary Arts Education',
  EDUA405: 'Pedagogy of Mathematics',
  EDUA516: 'Educational Media Design',
  EDUA630: 'Action Research in Educational Settings',
  ECE101: 'Introduction to Early Childhood Care & Education',
  MEDU402: 'Master Level Educational Leadership',
  MEDU406: 'Science Teaching Pedagogies',
  MEDU430: 'Advanced ICT in Education',
  MEDU601: 'Advanced Philosophy of Education',

  // Economics
  ECO401: 'Economics (Micro & Macro)',
  ECO402: 'Microeconomics Analysis',
  ECO403: 'Macroeconomics Analysis',
  ECO404: 'Managerial Economics',
  ECO406: 'Development Economics',
  ECO501: 'Monetary Economics',
  ECO601: 'International Economics',
  ECO603: 'Public Sector Economics',
  ECO606: 'Agricultural Economics',
  ECO607: 'Environmental & Resource Economics',
  ECO610: 'Econometrics Principles',

  // Management, Marketing & HRM
  MGT101: 'Financial Accounting',
  MGT111: 'Introduction to Public Administration',
  MGT211: 'Introduction to Business',
  MGT301: 'Principles of Marketing',
  MGT402: 'Cost & Management Accounting',
  MGT411: 'Money & Banking',
  MGT501: 'Human Resource Management',
  MGT502: 'Organizational Behaviour',
  MGT503: 'Principles of Management',
  MGT510: 'Total Quality Management',
  MGT602: 'Entrepreneurship',
  MGT604: 'Management of Financial Institutions',
  MGT610: 'Business Ethics & Corporate Governance',
  MGT611: 'Business & Labor Law',
  MGTE630: 'Business Management Strategy',
  MGMT614: 'Leadership & Team Building',
  MGMT615: 'Project Management Practices',
  MGMT617: 'Project Management Methodologies',
  MGMT622: 'Operations Management',
  MGMT623: 'Supply Chain Management',
  MGMT625: 'Knowledge Management Systems',
  MGMT627: 'Global Business Strategy',
  MGMT628: 'Strategic Management',
  MGMT630: 'Business Strategy & Policy',
  MGMT631: 'Innovation Management',
  MKT501: 'Marketing Management',
  MKT530: 'Consumer Behaviour',
  MKT610: 'Customer Relationship Management (CRM)',
  MKT621: 'Advertising & Brand Management',
  MKT630: 'International Marketing Strategy',
  HRM613: 'Human Resource Development',
  HRM617: 'Compensation & Benefits Management',
  HRM624: 'Conflict & Negotiation Management',
  HRM627: 'Strategic Human Resource Management',
  EMG525: 'Engineering Project Management',

  // Mass Communication & Media
  MCM000: 'Introduction to Communication Fundamentals',
  MCM101: 'Introduction to Mass Communication',
  MCM301: 'Communication Skills',
  MCM304: 'Mass Media in Pakistan',
  MCM310: 'Radio Broadcasting & Audio Media',
  MCM311: 'Radio & Television Production',
  MCM401: 'Fundamentals of Public Relations',
  MCM404: 'Electronic Media Content Creation',
  MCM411: 'News Writing and Reporting',
  MCM431: 'Digital Media & Online Journalism',
  MCM501: 'Development Support Communication',
  MCM511: 'Media Ethics, Cyber Laws & Regulation',
  MCM514: 'Feature, Column & Editorial Writing',
  MCM517: 'Advertising Strategy & Campaigns',
  MCM520: 'Print Media Design & Layout',
  MCM531: 'International & Cross-Cultural Communication',
  MCM601: 'Theories of Mass Communication',
  MCM604: 'Communication Research Methodology',
  MCM610: 'Cyber Journalism & Web Publishing',
  MCMP310: 'Radio & Audio Production Practical',
  MCD401: 'Media Content Development',
  MCD403: 'Media Ethics & Professional Standards',

  // Psychology & Sociology
  PSY101: 'General Psychology',
  PSY401: 'Clinical Psychology Fundamentals',
  PSY402: 'Social Psychology',
  PSY403: 'Developmental Psychology',
  PSY404: 'Abnormal Psychology',
  PSY405: 'Personality Theories & Assessment',
  PSY406: 'Educational Psychology Applications',
  PSY407: 'Experimental Psychology & Lab Methods',
  PSY408: 'Health Psychology',
  PSY502: 'History and Systems of Psychology',
  PSY504: 'Cognitive Psychology',
  PSY505: 'Psychological Testing & Measurement',
  PSY510: 'Positive Psychology & Well-being',
  PSY511: 'Counseling Psychology Principles',
  PSY512: 'Organizational & Industrial Psychology',
  PSY513: 'Neuropsychology Fundamentals',
  PSY515: 'Forensic & Criminal Psychology',
  PSY516: 'Cross-Cultural Psychology',
  PSY610: 'Neurological Basis of Behavior',
  PSY611: 'Psychopathology & Diagnostics',
  PSY631: 'Psychological Assessment Practicum',
  PSY632: 'Research Methods in Psychology',
  PSYP631: 'Psychological Assessment Lab Practical',
  SOC101: 'Introduction to Sociology',
  SOC201: 'Pakistani Society and Culture',
  SOC301: 'Social Psychology & Society',
  SOC302: 'Cultural Anthropology',
  SOC401: 'Social Research Methods',
  SOC402: 'Classical Sociological Theories',
  SOC403: 'Social Change & Modernization',
  SOC404: 'Urban Sociology',
  SOC601: 'Rural Sociology & Community Development',
  SOC602: 'Gender Studies & Society',
  SOC605: 'Criminology & Juvenile Delinquency',
  SOC608: 'Sociology of Development',
  SOC609: 'Sociology of Health & Medicine',
  SOC610: 'Demography & Population Dynamics',

  // Islamic Studies, Ethics, Pakistan Studies & Urdu
  ISL201: 'Islamic Studies',
  ISL202: 'Islamic Studies / Ethics',
  ETH100: 'Ethics (For Non-Muslim Students)',
  ETH201: 'Ethics & Moral Philosophy (For Non-Muslims)',
  PAK301: 'Pakistan Studies',
  PAK302: 'History of Pakistan',
  PAK522: 'Ideology & Constitution of Pakistan',
  URD101: 'Functional Urdu (Urdu Zaban-o-Adab)',
  URDU101: 'Urdu Language & Literature',
  GENERAL: 'General University Resources, Guides & Handbooks'
};

export function enrichCoursesFile() {
  const coursesPath = path.resolve('src/data/courses.json');
  if (!fs.existsSync(coursesPath)) return;

  const courses = JSON.parse(fs.readFileSync(coursesPath, 'utf-8'));
  let mapped = 0;

  for (const c of courses) {
    if (VU_OFFICIAL_TITLES[c.code]) {
      c.title = VU_OFFICIAL_TITLES[c.code];
      mapped++;
    }
  }

  fs.writeFileSync(coursesPath, JSON.stringify(courses, null, 2), 'utf-8');
  console.log(`✅ Successfully enriched courses catalog with ${mapped} official titles!`);
}

if (process.argv[1] && process.argv[1].endsWith('enrich-courses.ts')) {
  enrichCoursesFile();
}
